apiVersion: v1
kind: Config
clusters:
- name: "sandbox"
  cluster:
    server: "https://ec2-44-201-157-4.compute-1.amazonaws.com/k8s/clusters/c-gvtrf"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwekNDQ\
      VUyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
      GNOTWpJdwpOREF5TURVME5UVTBXaGNOTXpJd016TXdNRFUwTlRVMFdqQTdNUnd3R2dZRFZRUUtFe\
      E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
      1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNUMEN2TkhuSTExT\
      0ZJSWlMYnc0ZjRHcERzNVQ0R1o3Mkx1UlVXNTA3bApKWXROdU13WW90Yys1WDNuTC9Eckk5ODZJN\
      FdLTE1nZGU5T2hsdG93SHpJWG8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
      UgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVbTE3M3RGaEJPS3Rsa015dXhxdEYKMklpa1JKd3dDZ\
      1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSlgzN3F3cUhvRTdaRXNTYlpiTmxQTTBFbDB6WmlQRApBT\
      VhWY3JDT2FqaWZBaUFJVGsyMXFTR3VSajA1aFNmOXhQcFVmWVJHamttQVFmL1gwMGdFTndQaC9BP\
      T0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
- name: "sandbox-clsuter1"
  cluster:
    server: "https://34.207.133.254:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURRd01qQTJNelV3TlZvWERUTXlNRE16TURBMk16VXdOVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUtiY0J2bW5ML0V4CjNGeVdKamVtdkk5OWU1UTRJOFg2NGRLUzY1OWdkdWdmUWJXZTkxbHFoV\
      npkbU1weDFqTlpDN3pENzZQUDRjRkoKT3RpRGg1N2FoT0RJWDRHOENMYzFmb01jZndVQzJVVmhQT\
      jlCRnVrTGNPWGM4TGZZeFY5TmJDUjZYdW4xM3pCbwo4K1JMMjRudkFNSVN0MS8ySkZxb1AvTW91Z\
      GRxem9NK01jMTRMUEpFTG5zR2ZrWXoxaVBpaERhbUpUUkxPejJwCktkZE0zR0ZveUFLTUQ1akVuO\
      XNZUWxldVJqQktPditGMEhkN1dZUWFGZXhkSDdWdXdKR3VENzREZmU2QndzTFoKTlFUc0VEakZwd\
      Ew2dkxrNnF5WDUvcURYVDNLZ0R3MFNvd0pOS1JLNzdURkpOdldGcmlFN2Fka1N6QllpeWxwNgpFa\
      2J6dkc4NWZFVUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGQ1E2eXFYa1BDZ2FOOTVZVS9VSkJ1VHdJWEhjTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQTJ3czhmSjJoN0xYQTRxL1g3L0dubFBkUjEzdnA0b2c0YkhVR\
      k53cko2TlZuWnB5N2s1NVZmQmF6VAo3OHZUVG9RaERUMEJyNnd4N0RZU2Y3RnRIREN1ZjBmZGd3M\
      FV2RWU2RTY5MXhGc2doWG9QdzNadTljVHJiUHNuCkhaRHd0NEVqMUJwZE43Nk5hT3lyNEZZQXQzY\
      mRYVEtqQzFNbElybGh3WkZPcVpVb1RlaWI3M0dRRXh3OCszRTYKM0NzcjdQcWJMTEwwZmZ3aXhSM\
      2p5QzR1UGRRNitiT1VLQ21mTDU1WFY5bXJkRDA4emFaWmxBTkFyZFU0azBuOQpIOTFSejAxcUtlU\
      3JrOVdrSWhRQ04vS0hLSzl0VjRUWDd2SGh4MmpsLzYwMWZnbnpiVkV6Tk1LWkRoQnA3N0RjCkhOb\
      UJ4V2tnMTNDclNiWlh2QjdCVDJqOG00R0sKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "sandbox"
  user:
    token: "kubeconfig-user-dzngzjvlgf:gjh92s8c8cwzfdgtd2jrqgj27xln4r7trqpc5nqxts2j4glnqrvnjf"


contexts:
- name: "sandbox"
  context:
    user: "sandbox"
    cluster: "sandbox"
- name: "sandbox-clsuter1"
  context:
    user: "sandbox"
    cluster: "sandbox-clsuter1"

current-context: "sandbox"
